# Generated by Django 4.1.7 on 2023-05-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgeKeepers', '0002_face'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='encoding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
