# Generated by Django 4.1.7 on 2023-05-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgeKeepers', '0007_infos_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infos',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
