# Generated by Django 4.1.7 on 2023-05-08 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knowledgeKeepers', '0008_alter_infos_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('unique_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('selected', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
