# Generated by Django 4.1.7 on 2023-05-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgeKeepers', '0009_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='imageurl',
            field=models.TextField(default='', max_length=250),
        ),
    ]
