# Generated by Django 4.1.7 on 2023-05-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgeKeepers', '0011_avatar_mathcurrency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='mathcurrency',
        ),
        migrations.AddField(
            model_name='infos',
            name='mathcurrency',
            field=models.IntegerField(default=5),
        ),
    ]
