# Generated by Django 3.2.18 on 2023-05-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgeKeepers', '0014_remove_infos_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='infos',
            name='language',
            field=models.TextField(default='english', max_length=50),
        ),
    ]
